import UserDataTable from "@/components/users/users-table"

const mockUsers = [
    {
      id: "1",
      name: "John Doe",
      email: "john@example.com",
      status: "active" as const,
      plan: "pro",
      createdAt: new Date("2024-01-15"),
      revenue: 9900,
    },
    {
      id: "2",
      name: "Jane Smith",
      email: "jane@example.com",
      status: "churned" as const,
      plan: "free",
      createdAt: new Date("2024-03-05"),
      revenue: 0,
    },
    {
      id: "3",
      name: "Ali Khan",
      email: "ali@example.com",
      status: "active" as const,
      plan: "enterprise",
      createdAt: new Date("2024-02-10"),
      revenue: 29900,
    },
    {
      id: "4",
      name: "Sara Ahmed",
      email: "sara@example.com",
      status: "inactive" as const,
      plan: "starter",
      createdAt: new Date("2024-04-22"),
      revenue: 2900,
    },
    {
      id: "5",
      name: "Mike Johnson",
      email: "mike@example.com",
      status: "active" as const,
      plan: "pro",
      createdAt: new Date("2024-01-30"),
      revenue: 9900,
    },
    {
      id: "6",
      name: "Emily Chen",
      email: "emily@example.com",
      status: "active" as const,
      plan: "starter",
      createdAt: new Date("2024-05-12"),
      revenue: 2900,
    },
    {
      id: "7",
      name: "Omar Farooq",
      email: "omar@example.com",
      status: "churned" as const,
      plan: "pro",
      createdAt: new Date("2024-03-18"),
      revenue: 0,
    },
    {
      id: "8",
      name: "Lisa Wang",
      email: "lisa@example.com",
      status: "active" as const,
      plan: "enterprise",
      createdAt: new Date("2024-06-01"),
      revenue: 29900,
    },
    {
      id: "9",
      name: "David Brown",
      email: "david@example.com",
      status: "inactive" as const,
      plan: "free",
      createdAt: new Date("2024-02-28"),
      revenue: 0,
    },
    {
      id: "10",
      name: "Fatima Zahra",
      email: "fatima@example.com",
      status: "active" as const,
      plan: "starter",
      createdAt: new Date("2024-07-15"),
      revenue: 2900,
    },
    {
      id: "11",
      name: "James Wilson",
      email: "james@example.com",
      status: "active" as const,
      plan: "pro",
      createdAt: new Date("2024-04-05"),
      revenue: 9900,
    },
    {
      id: "12",
      name: "Aisha Malik",
      email: "aisha@example.com",
      status: "churned" as const,
      plan: "starter",
      createdAt: new Date("2024-08-20"),
      revenue: 0,
    },
    {
      id: "13",
      name: "Tom Harris",
      email: "tom@example.com",
      status: "active" as const,
      plan: "free",
      createdAt: new Date("2024-05-30"),
      revenue: 0,
    },
    {
      id: "14",
      name: "Maria Garcia",
      email: "maria@example.com",
      status: "inactive" as const,
      plan: "pro",
      createdAt: new Date("2024-09-10"),
      revenue: 9900,
    },
    {
      id: "15",
      name: "Hassan Ali",
      email: "hassan@example.com",
      status: "active" as const,
      plan: "enterprise",
      createdAt: new Date("2024-06-25"),
      revenue: 29900,
    },
    {
      id: "16",
      name: "Rachel Kim",
      email: "rachel@example.com",
      status: "active" as const,
      plan: "starter",
      createdAt: new Date("2024-10-03"),
      revenue: 2900,
    },
    {
      id: "17",
      name: "Usman Tariq",
      email: "usman@example.com",
      status: "churned" as const,
      plan: "free",
      createdAt: new Date("2024-07-14"),
      revenue: 0,
    },
    {
      id: "18",
      name: "Sophie Turner",
      email: "sophie@example.com",
      status: "active" as const,
      plan: "pro",
      createdAt: new Date("2024-11-22"),
      revenue: 9900,
    },
    {
      id: "19",
      name: "Zain Abbas",
      email: "zain@example.com",
      status: "inactive" as const,
      plan: "enterprise",
      createdAt: new Date("2024-08-08"),
      revenue: 29900,
    },
    {
      id: "20",
      name: "Anna Lee",
      email: "anna@example.com",
      status: "active" as const,
      plan: "starter",
      createdAt: new Date("2024-12-01"),
      revenue: 2900,
    },
  ]

  
export default function UsersPage(){
    return (
         <div className="p-6">
        <h1 className="text-3xl font-bold mb-1">Users</h1>
        <p className="text-muted-foreground mb-6">Manage your users and their subscriptions</p>
        <UserDataTable data={mockUsers} />
      </div>
    )
}